### PR TITLE
Move from Docker Hub to Google Artifact Registry

### PR DESCRIPTION
**Pull request by selfagency**
This update removes references to Docker Hub and Docker login and replaces them with Google Artifact Registry and Google Cloud login. It also fixes the build and test workflow to properly test a fresh build, as it was previously pulling the most recent image pushed.

### CODE REVIEW

**Comment by selfagency** [comment]
Related https://github.com/unstoppabledomains/unstoppable-domains-website/pull/3930

**Comment by bogdan** [comment]
@DeRain @aquiladev can you see if there is any impact of that on your side?

**Review by hivtushok — COMMENTED** [review]
LGTM

**Comment by aquiladev** [comment]
Can we clarify details of the changes. Do we still use same version of Zilliqa node(which we use before) or it is gonna be latest?

**Comment by selfagency** [comment]
You can specify a version tag when you deploy -- which you can now do [from a GitHub Action](https://github.com/unstoppabledomains/zns/actions/workflows/build-zilliqa-dev-node.yml) and not just the command line -- and both the version tag and `latest` tag will be applied as tags to the container image.

**Review by aquiladev — APPROVED** [review]

**Pull request merged**
